### ISSUE TITLE
401 Unauthorized error when I try to create MQTT connection in Ditto explorer UI or via curl command in bash

### ISSUE THREAD

**Issue by Felice-Copp56** [eclipse-ditto/ditto-examples#67] opened 2022-11-11 19:00 UTC
@thjaeckle Hi, I have deployed Eclipse ditto on my k8s cluster with the helm chart, the ditto-nginx service gateway is up and running at localhost:8080.
I can create policy, the thing but when I try to create connection for MQTT with js mapping in the Ditto explorer ui I got a 401 unauthorized error, I have used devops and foobar credentials.
Also, I have tried to create the connection via curl command on bash by following this tutorial https://github.com/eclipse-ditto/ditto-examples/blob/master/mqtt-bidirectional/README.md, in this case MQTT pub and sub works on the bash but on my web browser I can't see any update of my device.
Any idea?

**Comment by thjaeckle** [comment] 2022-11-23 07:11
Duplicate of https://github.com/eclipse-ditto/ditto/issues/1533

**Closed by thjaeckle** 2022-11-23 07:11 UTC
